"""Re-introduce vehicles with correct structure

Revision ID: 67b9bf78fb03
Revises: d39e713ec938
Create Date: 2025-10-08 15:09:31.542475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67b9bf78fb03'
down_revision: Union[str, Sequence[str], None] = 'd39e713ec938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'created_at')
    # ### end Alembic commands ###
