"""Remove device fields and unique constraint

Revision ID: d39e713ec938
Revises: cdb60e15e44b
Create Date: 2025-10-03 11:23:22.153694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd39e713ec938'
down_revision: Union[str, Sequence[str], None] = 'cdb60e15e44b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_logs_device_time'), table_name='device_logs')
    op.drop_index(op.f('idx_logs_journey_time'), table_name='device_logs')
    op.drop_index(op.f('idx_logs_recent'), table_name='device_logs')
    op.drop_constraint(op.f('devices_serial_number_key'), 'devices', type_='unique')
    op.drop_column('devices', 'device_name')
    op.drop_column('devices', 'description')
    op.drop_column('devices', 'device_type')
    op.drop_index(op.f('idx_journey_status_time'), table_name='journey_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_journey_status_time'), 'journey_sessions', ['status', 'start_time', 'end_time'], unique=False)
    op.add_column('devices', sa.Column('device_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('device_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('devices_serial_number_key'), 'devices', ['serial_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_logs_recent'), 'device_logs', [sa.literal_column('collected_at DESC')], unique=False)
    op.create_index(op.f('idx_logs_journey_time'), 'device_logs', ['journey_session_id', sa.literal_column('collected_at DESC')], unique=False)
    op.create_index(op.f('idx_logs_device_time'), 'device_logs', ['device_imei', sa.literal_column('collected_at DESC')], unique=False)
    # ### end Alembic commands ###
