version: '3.8'

services:
  db:
    image: timescale/timescaledb:latest-pg14
    container_name: obu_db_backend
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=obu_service
    ports:
      - "5432:5432"
    volumes:
      - obu_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: obu_redis
    ports:
      - "6379:6379"
    volumes:
      - obu_redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

  # api-service:
  #   container_name: obu_api_service
  #   build:
  #     context: ../services/api-service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #     - redis
  #   restart: unless-stopped
  #   environment:
  #     - DATABASE_URL=postgresql://admin:password@db:5432/obu_service
  #     - REDIS_URL=redis://redis:6379/0

volumes:
  obu_db_data:
    name: obu_db_volume
  obu_redis_data:
    name: obu_redis_volume

